# Generated by Django 5.0.3 on 2026-05-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('low_stock_threshold', models.FloatField(default=0)),
            ],
        ),
    ]
