# Generated by Django 5.0.3 on 2026-05-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_initial'),
        ('recipes', '0002_ingredient_calories_per_unit_and_more'),
        ('users', '0002_household_invite_code_household_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pantryitem',
            options={'ordering': ['ingredient__name']},
        ),
        migrations.AddConstraint(
            model_name='pantryitem',
            constraint=models.UniqueConstraint(fields=('household', 'ingredient', 'unit'), name='unique_pantry_item_unit'),
        ),
    ]
