# Generated by Django 5.0.3 on 2026-05-27 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_initial'),
        ('recipes', '0002_ingredient_calories_per_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryitem',
            options={'ordering': ['ingredient__category', 'ingredient__name']},
        ),
        migrations.AlterModelOptions(
            name='grocerylist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='estimated_cost_xaf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='manually_adjusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('shopping', 'Shopping'), ('completed', 'Completed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='total_estimated_cost_xaf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='groceryitem',
            constraint=models.UniqueConstraint(fields=('grocery_list', 'ingredient', 'unit'), name='unique_grocery_item_unit'),
        ),
    ]
