# Generated by Django 5.0.3 on 2026-05-27 20:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_meal_recipe_name_alter_meal_recipe'),
        ('recipes', '0002_ingredient_calories_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['date', 'meal_type']},
        ),
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='meal',
            name='ai_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meal',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI suggested')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='title',
            field=models.CharField(default='Weekly Meal Plan', max_length=255),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='weekly_budget_xaf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('meal_plan', 'date', 'meal_type'), name='unique_meal_slot'),
        ),
    ]
