# Generated by Django 5.0.3 on 2026-05-28 04:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_meal_options_alter_mealplan_options_and_more'),
        ('recipes', '0002_ingredient_calories_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='entry_type',
            field=models.CharField(choices=[('recipe', 'Existing recipe'), ('custom', 'Custom meal')], default='recipe', max_length=20),
        ),
        migrations.CreateModel(
            name='MealAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('estimated_total_cost_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nutrition_strength_score', models.FloatField(default=0)),
                ('nutrition_strength', models.CharField(default='Needs review', max_length=80)),
                ('health_benefits', models.JSONField(blank=True, default=list)),
                ('health_risks', models.JSONField(blank=True, default=list)),
                ('advisory_summary', models.TextField(blank=True)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0)),
                ('is_estimated', models.BooleanField(default=True)),
                ('provider', models.CharField(default='local', max_length=50)),
                ('status', models.CharField(choices=[('local', 'Local calculation'), ('ai', 'AI estimated'), ('fallback', 'Fallback estimate'), ('error', 'Analysis error')], default='local', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='meals.meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(default='g', max_length=50)),
                ('unit_price_xaf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_ingredients', to='meals.meal')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
