// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDAlIBIKSS5Dah8J521rS6unOHit-vKEA',
    appId: '1:360954874888:web:01702a272840cb657695bd',
    messagingSenderId: '360954874888',
    projectId: 'eatfits',
    authDomain: 'eatfits.firebaseapp.com',
    storageBucket: 'eatfits.firebasestorage.app',
    measurementId: 'G-LYCE4Z8TV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu1SqwX0u8NDlaHImu1qhITyZa0e0rPy0',
    appId: '1:360954874888:android:4e695736934de71f7695bd',
    messagingSenderId: '360954874888',
    projectId: 'eatfits',
    storageBucket: 'eatfits.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxxS-DOCOLo9OIU8HQVlt-xVmk25secvY',
    appId: '1:360954874888:ios:c36e327077f0dfb77695bd',
    messagingSenderId: '360954874888',
    projectId: 'eatfits',
    storageBucket: 'eatfits.firebasestorage.app',
    iosBundleId: 'com.example.eatfits',
  );
}
