# Generated by Django 5.0.3 on 2026-05-27 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='invite_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='household',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='HouseholdMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(choices=[('none', 'No restriction'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('high_protein', 'High protein'), ('low_carb', 'Low carb')], default='none', max_length=30)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('likes', models.JSONField(blank=True, default=list)),
                ('dislikes', models.JSONField(blank=True, default=list)),
                ('calorie_goal', models.PositiveIntegerField(default=2200)),
                ('protein_goal', models.PositiveIntegerField(default=100)),
                ('carbs_goal', models.PositiveIntegerField(default=250)),
                ('fat_goal', models.PositiveIntegerField(default=70)),
                ('weekly_budget_xaf', models.PositiveIntegerField(default=35000)),
                ('timezone', models.CharField(default='Africa/Douala', max_length=64)),
                ('measurement_system', models.CharField(default='metric', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='householdmembership',
            constraint=models.UniqueConstraint(fields=('user', 'household'), name='unique_household_membership'),
        ),
    ]
