# Generated by Django 5.0.3 on 2026-05-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiinteractionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='aiinteractionlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='aiinteractionlog',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='aiinteractionlog',
            name='response',
        ),
        migrations.AddField(
            model_name='aiinteractionlog',
            name='input_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='aiinteractionlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiinteractionlog',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aiinteractionlog',
            name='operation',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='aiinteractionlog',
            name='output_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aiinteractionlog',
            name='provider',
            field=models.CharField(default='openai', max_length=50),
        ),
        migrations.AddField(
            model_name='aiinteractionlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('fallback', 'Fallback'), ('error', 'Error')], default='success', max_length=20),
        ),
    ]
